sudo: required
services: 
 - docker

before_install:
 - docker build -t sondang86/docker-reactjs-travis -f Dockerfile.dev .

script:
 - docker run CI=true sondang86/docker-reactjs-travis npm run test
